moveList = {
    'Acid': {
        'Name': 'Acid',
        'Effect': 'unboost',
        'Odds': 10,
    },
    'Aurora Beam': {
        'Name': 'Aurora Beam',
        'Effect': 'unboost',
        'Odds': 10,
    },
    'Bite': {
        'Name': 'Bite',
        'Effect': 'flinch',
        'Odds': 10,
    },
    'Blizzard': {
        'Name': 'Blizzard',
        'Effect': 'frz',
        'Odds': 10,
    },
    'Body Slam': {
        'Name': 'Body Slam',
        'Effect': 'par',
        'Odds': 30,
    },
    'Bone Club': {
        'Name': 'Bone Club',
        'Effect': 'flinch',
        'Odds': 10,
    },
    'Bubble': {
        'Name': 'Bubble',
        'Effect': 'unboost',
        'Odds': 10,
    },
    'Bubble Beam': {
        'Name': 'Bubble Beam',
        'Effect': 'unboost',
        'Odds': 10,
    },
    'Confusion': {
        'Name': 'Confusion',
        'Effect': 'confusion',
        'Odds': 10,
    },
    'Constrict': {
        'Name': 'Constrict',
        'Effect': 'unboost',
        'Odds': 10,
    },
    'Ember': {
        'Name': 'Ember',
        'Effect': 'brn',
        'Odds': 10,
    },
    'Fire Blast': {
        'Name': 'Fire Blast',
        'Effect': 'brn',
        'Odds': 30,
    },
    'Fire Punch': {
        'Name': 'Fire Punch',
        'Effect': 'brn',
        'Odds': 10,
    },
    'Flamethrower': {
        'Name': 'Flamethrower',
        'Effect': 'brn',
        'Odds': 10,
    },
    'Headbutt': {
        'Name': 'Headbutt',
        'Effect': 'flinch',
        'Odds': 30,
    },
    'Hyper Fang': {
        'Name': 'Hyper Fang',
        'Effect': 'flinch',
        'Odds': 10,
    },
    'Ice Beam': {
        'Name': 'Ice Beam',
        'Effect': 'frz',
        'Odds': 10,
    },
    'Ice Punch': {
        'Name': 'Ice Punch',
        'Effect': 'frz',
        'Odds': 10,
    },
    'Lick': {
        'Name': 'Lick',
        'Effect': 'par',
        'Odds': 30,
    },
    'Low Kick': {
        'Name': 'Low Kick',
        'Effect': 'flinch',
        'Odds': 30,
    },
    'Poison Sting': {
        'Name': 'Poison Sting',
        'Effect': 'psn',
        'Odds': 20,
    },
    'Psybeam': {
        'Name': 'Psybeam',
        'Effect': 'confusion',
        'Odds': 10,
    },
    'Psychic': {
        'Name': 'Psychic',
        'Effect': 'unboost',
        'Odds': 33,
    },
    'Rolling Kick': {
        'Name': 'Rolling Kick',
        'Effect': 'flinch',
        'Odds': 30,
    },
    'Sludge': {
        'Name': 'Sludge',
        'Effect': 'psn',
        'Odds': 30,
    },
    'Smog': {
        'Name': 'Smog',
        'Effect': 'psn',
        'Odds': 30,
    },
    'Thunder': {
        'Name': 'Thunder',
        'Effect': 'par',
        'Odds': 10,
    },
    'Thunderbolt': {
        'Name': 'Thunderbolt',
        'Effect': 'par',
        'Odds': 10,
    },
    'Thunder Punch': {
        'Name': 'Thunder Punch',
        'Effect': 'par',
        'Odds': 10,
    },
    'Thunder Shock': {
        'Name': 'Thunder Shock',
        'Effect': 'par',
        'Odds': 10,
    },
    'Twineedle': {
        'Name': 'Twineedle',
        'Effect': 'psn',
        'Odds': 20,
    },
}

# ['Acid', ['unboost', 'def|1',target['nickname'], .1,f"{target['pokemon']} suffered a stat drop via secondary effect by {attacker['pokemon']} with {move}"]],
# ['Aurora Beam', ['unboost', 'atk|1',target['nickname'], .1,f"{target['pokemon']} suffered a stat drop via secondary effect by {attacker['pokemon']} with {move}"]],
# ['Bite', ['cant', 'flinch',target['nickname'], .1,f"{target['pokemon']} was flinched by {attacker['pokemon']} with {move}"]],
# ['Blizzard', ['status', 'frz',target['nickname'],.1,f"{target['pokemon']} was frozen by {attacker['pokemon']} with {move}"]],
# ['Body Slam', ['status', 'par',target['nickname'],.3,f"{target['pokemon']} was paralyzed by {attacker['pokemon']} with {move}"]],
# ['Bone Club', ['cant', 'flinch',target['nickname'], .1,f"{target['pokemon']} was flinched by {attacker['pokemon']} with {move}"]],
# ['Bubble', ['unboost', 'spe|1',target['nickname'], .1,f"{target['pokemon']} suffered a stat drop via secondary effect by {attacker['pokemon']} with {move}"]],
# ['Bubble Beam', ['unboost', 'spe|1',target['nickname'], .1,f"{target['pokemon']} suffered a stat drop via secondary effect by {attacker['pokemon']} with {move}"]],
# ['Confusion', ['start', 'confusion',target['nickname'], .1,f"{target['pokemon']} was confused by {attacker['pokemon']} with {move}"]],
# ['Constrict', ['unboost', 'spe|1',target['nickname'], .1,f"{target['pokemon']} suffered a stat drop via secondary effect by {attacker['pokemon']} with {move}"]],
# ['Ember', ['status', 'brn',target['nickname'],.1,f"{target['pokemon']} was burned by {attacker['pokemon']} with {move}"]],
# ['Fire Blast', ['status', 'brn',target['nickname'],.3,f"{target['pokemon']} was burned by {attacker['pokemon']} with {move}"]],
# ['Fire Punch', ['status', 'brn',target['nickname'],.1,f"{target['pokemon']} was burned by {attacker['pokemon']} with {move}"]],
# ['Flamethrower', ['status', 'brn',target['nickname'],.1,f"{target['pokemon']} was burned by {attacker['pokemon']} with {move}"]],
# ['Headbutt', ['cant', 'flinch', target['nickname'], .3, f"{target['pokemon']} was flinched by {attacker['pokemon']} with {move}"]],
# ['Hyper Fang', ['cant', 'flinch', target['nickname'], .1, f"{target['pokemon']} was flinched by {attacker['pokemon']} with {move}"]],
# ['Ice Beam', ['status', 'frz',target['nickname'],.1,f"{target['pokemon']} was frozen by {attacker['pokemon']} with {move}"]],
# ['Ice Punch', ['status', 'frz',target['nickname'],.1,f"{target['pokemon']} was frozen by {attacker['pokemon']} with {move}"]],
# ['Lick', ['status', 'par',target['nickname'],.3,f"{target['pokemon']} was paralyzed by {attacker['pokemon']} with {move}"]],
# ['Low Kick', ['cant', 'flinch', target['nickname'], .3, f"{target['pokemon']} was flinched by {attacker['pokemon']} with {move}"]],
# ['Poison Sting', ['status', 'psn',target['nickname'],.2,f"{target['pokemon']} was poisoned by {attacker['pokemon']} with {move}"]],
# ['Psybeam', ['start', 'confusion',target['nickname'], .1,f"{target['pokemon']} was confused by {attacker['pokemon']} with {move}"]],
# ['Psychic', ['unboost', 'spa|1',target['nickname'], .33,f"{target['pokemon']} suffered a stat drop via secondary effect by {attacker['pokemon']} with {move}"]],
# ['Rolling Kick', ['cant', 'flinch', target['nickname'], .3, f"{target['pokemon']} was flinched by {attacker['pokemon']} with {move}"]],
# ['Sludge', ['status', 'psn',target['nickname'],.3,f"{target['pokemon']} was poisoned by {attacker['pokemon']} with {move}"]],
# ['Smog', ['status', 'psn',target['nickname'],.3,f"{target['pokemon']} was poisoned by {attacker['pokemon']} with {move}"]],
# ['Thunder', ['status', 'par',target['nickname'],.1,f"{target['pokemon']} was paralyzed by {attacker['pokemon']} with {move}"]],
# ['Thunderbolt', ['status', 'par',target['nickname'],.1,f"{target['pokemon']} was paralyzed by {attacker['pokemon']} with {move}"]],
# ['Thunder Punch', ['status', 'par',target['nickname'],.1,f"{target['pokemon']} was paralyzed by {attacker['pokemon']} with {move}"]],
# ['Thunder Shock', ['status', 'par',target['nickname'],.1,f"{target['pokemon']} was paralyzed by {attacker['pokemon']} with {move}"]],
# ['Twineedle', ['status', 'psn',target['nickname'],.2,f"{target['pokemon']} was poisoned by {attacker['pokemon']} with {move}"]],])